"""Protocol models, validation, identities, references, and pagination."""

from offering_protocol.core.models import *  # noqa: F403
from offering_protocol.core.models import __all__ as _models_all
from offering_protocol.core.references import (
    ReferenceError,
    build_operation_url,
    create_resource_identity,
    derive_service_origin,
    is_local_resource_identifier,
    operation_method,
    operation_path,
    resolve_continuation,
    resolve_resource_reference,
)
from offering_protocol.core.validation import (
    OdpValidationError,
    ValidationIssue,
    parse_collection,
    parse_collection_page,
    parse_collection_search_request,
    parse_filter_definition,
    parse_filter_definition_page,
    parse_offering,
    parse_offering_page,
    parse_offering_search_request,
    parse_problem_details,
    parse_problem_response,
    parse_resource_identity,
    parse_service_document,
    parse_sort_definition,
    parse_sort_definition_page,
    validate_value,
)

__all__ = [
    *_models_all,
    "OdpValidationError",
    "ReferenceError",
    "ValidationIssue",
    "build_operation_url",
    "create_resource_identity",
    "derive_service_origin",
    "is_local_resource_identifier",
    "operation_method",
    "operation_path",
    "parse_collection",
    "parse_collection_page",
    "parse_collection_search_request",
    "parse_filter_definition",
    "parse_filter_definition_page",
    "parse_offering",
    "parse_offering_page",
    "parse_offering_search_request",
    "parse_problem_details",
    "parse_problem_response",
    "parse_resource_identity",
    "parse_service_document",
    "parse_sort_definition",
    "parse_sort_definition_page",
    "resolve_continuation",
    "resolve_resource_reference",
    "validate_value",
]
